# Generated by Django 5.0.7 on 2024-08-04 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivraisonVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison', models.DateTimeField()),
                ('adresse_livraison', models.TextField()),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.piece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ManyToManyField(to='sell.order')),
            ],
        ),
        migrations.CreateModel(
            name='VenteCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('channels', models.CharField(max_length=10)),
                ('transaction_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('return_url', models.URLField()),
                ('notify_url', models.URLField()),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_surname', models.CharField(max_length=50)),
                ('response', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='VentePieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('channels', models.CharField(max_length=10)),
                ('transaction_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('return_url', models.URLField()),
                ('notify_url', models.URLField()),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_surname', models.CharField(max_length=50)),
                ('response', models.JSONField(blank=True, null=True)),
                ('PieceVehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.vehicule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
