# Generated by Django 5.0.7 on 2024-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
