# Generated by Django 5.0.7 on 2024-08-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_livraisonadresse_delete_livraisonvehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventecars',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='ventecars',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.cart'),
        ),
        migrations.DeleteModel(
            name='VentePieces',
        ),
    ]
