# Generated by Django 5.0.7 on 2024-08-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_remove_ventecars_vehicule_ventecars_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
